</div>

<footer>
    <div class="footer-wrapper">
        <div class="dmca-wrapper">
            <!-- For dmca -->
        </div>
        <div class="copyright">Copyright © 2020</div>
    </div>
</footer>

<div id="popupContainer">
    <div style="position: absolute; top: 50%; left: 50%; margin-right: -50%;">
        <div class="popup-container" style="width: 100%; max-width: 345px; padding-bottom: 50px; position: fixed; z-index: 99990; left: 44%; margin-left: -150px; background: url(&quot;https://cdn.backyard.ltd/popups/orange.png&quot;) 50% 0% / cover no-repeat, center center; top: 10%; display: none; flex-direction: column; text-transform: none;">
            <button class="popup-close" style="width: 20px; height: 20px; margin-left: auto; background: url(&quot;https://cdn.backyard.ltd/popups/group.png&quot;) no-repeat, center center; border: none; position: absolute; top: 20px; right: 10px; outline: 0px; box-shadow: unset;"></button>
            <p class="popup-heading" style="margin-top: 176px; text-align: center; font-family: Roboto, sans-serif; font-style: normal; font-weight: 900; font-size: 21px; line-height: 26px; color: rgb(35, 35, 35); letter-spacing: 0.2px;">5 портфелей инвестора</p>
            <p class="popup-description" style="margin: 0px auto; width: 100%; max-width: 298px; height: 64px; text-align: center; font-family: Roboto, sans-serif; font-style: normal; font-weight: 400; font-size: 14px; line-height: 16px; color: rgb(0, 0, 0); padding-top: 20px;">Узнайте, какие топ-5 инвестпортфелей приносят повышенный доход трейдерам. Получите свой набор для прибыли и торгуйте еще увереннее!</p>
            <a class="popup-top-button" href="https://protate.live/www/delivery/ck.php?oaparams=2__bannerid=285__zoneid=11__source=https%3A%2F%2Fmaximarkets.group__cb=a012f45d2e__oadest=https://r.maximarkets.org/?linkid=oth-sat-investment-portfolio-popup-ru&amp;sky=maximarkets.group" style="width: 305px; height: 59px; background: rgb(244, 108, 31); border: none; font-family: Roboto, sans-serif; font-style: normal; font-weight: 500; font-size: 16px; line-height: 59px; text-align: center; color: rgb(255, 255, 255); margin: 40px auto 0px; display: flex; align-items: center; justify-content: center;">Получить портфель</a>
            <a class="popup-bottom-button" style="width: 305px; height: 59px; background: rgb(238, 170, 132); border: none; font-family: Roboto, sans-serif; font-style: normal; font-weight: 300; font-size: 16px; line-height: 59px; text-align: center; color: rgb(255, 255, 255); margin: 10px auto 0px; display: flex; align-items: center; justify-content: center;">Не интересно</a>
        </div>
        <div class="popup-container" style="width: 100%; max-width: 345px; padding-bottom: 50px; position: fixed; z-index: 99990; left: 44%; margin-left: -150px; background: url(&quot;https://cdn.backyard.ltd/popups/red.png&quot;) 50% 0% / cover no-repeat, center center; top: 10%; display: none; flex-direction: column; text-transform: none;">
            <button class="popup-close" style="width: 20px; height: 20px; margin-left: auto; background: url(&quot;https://cdn.backyard.ltd/popups/group.png&quot;) no-repeat, center center; border: none; position: absolute; top: 20px; right: 10px; outline: 0px; box-shadow: unset;"></button>
            <p class="popup-heading" style="margin-top: 176px; text-align: center; font-family: Roboto, sans-serif; font-style: normal; font-weight: 900; font-size: 21px; line-height: 26px; color: rgb(35, 35, 35); letter-spacing: 0.2px;">Двойной бонус на счет</p>
            <p class="popup-description" style="margin: 0px auto; width: 100%; max-width: 298px; height: 64px; text-align: center; font-family: Roboto, sans-serif; font-style: normal; font-weight: 400; font-size: 14px; line-height: 16px; color: rgb(0, 0, 0); padding-top: 20px;">Удвойте ваш депозит и результат в торговле. Получите 100% бонус на счет и начните зарабатывать!</p>
            <a class="popup-top-button" href="https://protate.live/www/delivery/ck.php?oaparams=2__bannerid=285__zoneid=11__source=https%3A%2F%2Fmaximarkets.group__cb=a012f45d2e__oadest=https://r.maximarkets.org/?linkid=oth-sat-bonus-popup-ru&amp;sky=maximarkets.group" style="width: 305px; height: 59px; background: rgb(244, 31, 31); border: none; font-family: Roboto, sans-serif; font-style: normal; font-weight: 500; font-size: 16px; line-height: 59px; text-align: center; color: rgb(255, 255, 255); margin: 40px auto 0px; display: flex; align-items: center; justify-content: center;">Получить бонус</a><a class="popup-bottom-button" style="width: 305px; height: 59px; background: rgb(228, 142, 142); border: none; font-family: Roboto, sans-serif; font-style: normal; font-weight: 300; font-size: 16px; line-height: 59px; text-align: center; color: rgb(255, 255, 255); margin: 10px auto 0px; display: flex; align-items: center; justify-content: center;">В другой раз</a>
        </div>
        <div class="popup-container" style="width: 100%; max-width: 345px; padding-bottom: 50px; position: fixed; z-index: 99990; left: 44%; margin-left: -150px; background: url(&quot;https://cdn.backyard.ltd/popups/blue.png&quot;) 50% 0% / cover no-repeat, center center; top: 10%; display: none; flex-direction: column; text-transform: none;">
            <button class="popup-close" style="width: 20px; height: 20px; margin-left: auto; background: url(&quot;https://cdn.backyard.ltd/popups/group.png&quot;) no-repeat, center center; border: none; position: absolute; top: 20px; right: 10px; outline: 0px; box-shadow: unset;"></button>
            <p class="popup-heading" style="margin-top: 176px; text-align: center; font-family: Roboto, sans-serif; font-style: normal; font-weight: 900; font-size: 21px; line-height: 26px; color: rgb(35, 35, 35); letter-spacing: 0.2px;">Тест на трейдера</p>
            <p class="popup-description" style="margin: 0px auto; width: 100%; max-width: 298px; height: 64px; text-align: center; font-family: Roboto, sans-serif; font-style: normal; font-weight: 400; font-size: 14px; line-height: 16px; color: rgb(0, 0, 0); padding-top: 20px;"> По статистике финансовый успех зависит от качеств, которыми обладают 70% людей. Пройдите тест из 10 вопросов и узнайте, сможете ли вы заработать на бирже!</p>
            <a class="popup-top-button" href="https://protate.live/www/delivery/ck.php?oaparams=2__bannerid=285__zoneid=11__source=https%3A%2F%2Fmaximarkets.group__cb=a012f45d2e__oadest=https://r.umarkets.com/?linkid=oth-sat-quiz-popup-um-ru&amp;sky=maximarkets.group" style="width: 305px; height: 59px; background: rgb(31, 103, 244); border: none; font-family: Roboto, sans-serif; font-style: normal; font-weight: 500; font-size: 16px; line-height: 59px; text-align: center; color: rgb(255, 255, 255); margin: 40px auto 0px; display: flex; align-items: center; justify-content: center;">Пройти тест</a><a class="popup-bottom-button" style="width: 305px; height: 59px; background: rgb(142, 175, 200); border: none; font-family: Roboto, sans-serif; font-style: normal; font-weight: 300; font-size: 16px; line-height: 59px; text-align: center; color: rgb(255, 255, 255); margin: 10px auto 0px; display: flex; align-items: center; justify-content: center;">Спасибо, не хочу</a>
        </div>
        <div class="popup-container" style="width: 100%; max-width: 345px; padding-bottom: 50px; position: fixed; z-index: 99990; left: 44%; margin-left: -150px; background: url(&quot;https://cdn.backyard.ltd/popups/green.png&quot;) 50% 0% / cover no-repeat, center center; top: 10%; display: none; flex-direction: column; text-transform: none;">
            <button class="popup-close" style="width: 20px; height: 20px; margin-left: auto; background: url(&quot;https://cdn.backyard.ltd/popups/group.png&quot;) no-repeat, center center; border: none; position: absolute; top: 20px; right: 10px; outline: 0px; box-shadow: unset;"></button>
            <p class="popup-heading" style="margin-top: 176px; text-align: center; font-family: Roboto, sans-serif; font-style: normal; font-weight: 900; font-size: 21px; line-height: 26px; color: rgb(35, 35, 35); letter-spacing: 0.2px;">СМС-аналитика бесплатно</p>
            <p class="popup-description" style="margin: 0px auto; width: 100%; max-width: 298px; height: 64px; text-align: center; font-family: Roboto, sans-serif; font-style: normal; font-weight: 400; font-size: 14px; line-height: 16px; color: rgb(0, 0, 0); padding-top: 20px;">Успешный трейдер не следит за трендами 24/7, а получает помощь экспертов. Подпишитесь на СМС-сигналы и открывайте еще больше прибыльных сделок!</p>
            <a class="popup-top-button" href="https://protate.live/www/delivery/ck.php?oaparams=2__bannerid=285__zoneid=11__source=https%3A%2F%2Fmaximarkets.group__cb=a012f45d2e__oadest=https://r.umarkets.com/?linkid=oth-sat-sms-signals-popup-um-ru&amp;sky=maximarkets.group" style="width: 305px; height: 59px; background: rgb(10, 196, 129); border: none; font-family: Roboto, sans-serif; font-style: normal; font-weight: 500; font-size: 16px; line-height: 59px; text-align: center; color: rgb(255, 255, 255); margin: 40px auto 0px; display: flex; align-items: center; justify-content: center;">Подписаться</a><a class="popup-bottom-button" style="width: 305px; height: 59px; background: rgb(129, 198, 173); border: none; font-family: Roboto, sans-serif; font-style: normal; font-weight: 300; font-size: 16px; line-height: 59px; text-align: center; color: rgb(255, 255, 255); margin: 10px auto 0px; display: flex; align-items: center; justify-content: center;">Спасибо, не интересует</a>
        </div>
    </div>
</div>

<?php wp_footer(); ?>
</body>
</html>